/****************************** ghost1372.github.io ******************************\
*	Module Name:	Settings.xaml.cs
*	Project:		MoalemYar
*	Copyright (C) 2017 Mahdi Hosseini, All rights reserved.
*	This software may be modified and distributed under the terms of the MIT license.  See LICENSE file for details.
*
*	Written by Mahdi Hosseini <Mahdidvb72@gmail.com>,  2018, 3, 28, 05:42 ب.ظ
*
***********************************************************************************/

using System;
using System.Collections.ObjectModel;
using System.Data.Entity;
using System.Data.SQLite;
using System.IO;
using System.Linq;
using System.Windows;
using System.Windows.Controls;

namespace MoalemYar.UserControls
{
    /// <summary>
    /// Interaction logic for Settings.xaml
    /// </summary>
    public partial class SettingsView : UserControl
    {
        private ObservableCollection<string> list = new ObservableCollection<string>();

        internal static SettingsView main;

        public SettingsView()
        {
            InitializeComponent();

            getSchool();
            
            main = this;
            LoadSettings();
        }

        #region Async Query

        private void getSchool()
        {
            try
            {
                using (var db = new DataClass.myDbContext())
                {
                    var query = db.Schools.ToList();
                    cmbBase.ItemsSource = query.Any() ? query : null;
                }
            }
            catch (Exception)
            {
            }
        }

        #endregion Async Query

        private void LoadSettings()
        {
            loadServers();
            if (FindElement.Settings.CredentialLogin)
                swLogin.IsChecked = true;
            else
                swLogin.IsChecked = false;

            if (FindElement.Settings.Autorun)
                swAutoStart.IsChecked = true;
            else
                swAutoStart.IsChecked = false;            
        }
  
        private void swLogin_Checked(object sender, RoutedEventArgs e)
        {
            FindElement.Settings.CredentialLogin = Convert.ToBoolean(swLogin.IsChecked);
        }

        private void swAutoStart_Checked(object sender, RoutedEventArgs e)
        {
            FindElement.Settings.Autorun = Convert.ToBoolean(swAutoStart.IsChecked);
            AppVariable.RegisterInStartup(Convert.ToBoolean(swAutoStart.IsChecked));
        }

        private void Hamborger_Menu_Checked(object sender, RoutedEventArgs e)
        {
            //Todo: Fix
            //FindElement.Settings.HamburgerMenu = Hamborger_Menu.IsChecked;
            //MainWindow.main.tab.IconMode = Convert.ToBoolean(!Hamborger_Menu.IsChecked);
        }

        private void btnFactoryReset_Click(object sender, RoutedEventArgs e)
        {
            MainWindow.main.ResetDataConfirmNotification("تنظیمات برنامه");
        }

        public void resetConfig()
        {
            string folder = AppVariable.fileName + @"\config.json";
            if (System.IO.File.Exists(folder))
            {
                File.Delete(folder);
                MainWindow.main.DataResetDeletedNotification("تنظیمات برنامه");
            }
        }

        public void resetDatabase()
        {
            string folder = AppVariable.fileName + @"\data.db";
            try
            {
                if (System.IO.File.Exists(folder))
                {
                    cmbBase.ItemsSource = null;
                    File.Delete(folder);

                    //Todo: Fix
                    //MainWindow.main.exAddOrUpdateSchool.Hint = "0";
                    //MainWindow.main.exAddOrUpdateStudent.Hint = "0";
                    //MainWindow.main.exAddOrUpdateUser.Hint = "0";
                    MainWindow.main.DataResetDeletedNotification("دیتابیس برنامه");
                    using (var context = new DataClass.myDbContext())
                    {
                        CreateAndSeedDatabase(context);
                    }
                }
            }
            catch (IOException)
            {
            }
        }

        private static void CreateAndSeedDatabase(DbContext context)
        {
            context.Database.Initialize(true);
            try
            {
                if (context.Set<DataClass.Tables.User>().Count() != 0)
                {
                    return;
                }
                context.Set<DataClass.Tables.User>().Add(new DataClass.Tables.User
                {
                    Username = "test",
                    Password = "test"
                });

                context.SaveChanges();
            }
            catch (Exception)
            {
            }
        }

        private void btnDatabaseReset_Click(object sender, RoutedEventArgs e)
        {
            MainWindow.main.ResetDataConfirmNotification("دیتابیس برنامه");
        }

        private void cmbChart_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            var element = sender as ComboBox;
            FindElement.Settings.ChartType = element.SelectedIndex;
        }

        private void cmbChartColor_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            var element = sender as ComboBox;
            FindElement.Settings.ChartColorIndex = element.SelectedIndex;
            switch (element.SelectedIndex)
            {
                case 0:
                    FindElement.Settings.ChartColor = AppVariable.CHART_GREEN;
                    break;

                case 1:
                    FindElement.Settings.ChartColor = AppVariable.CHART_PURPLE;
                    break;

                case 2:
                    FindElement.Settings.ChartColor = AppVariable.CHART_ORANGE;
                    break;
            }
        }

        private void UserControl_Loaded(object sender, RoutedEventArgs e)
        {
            var elementType = FindElement.FindElementByName<ComboBox>(cmbChartType, "cmbChart");
            var elementColor = FindElement.FindElementByName<ComboBox>(cmbChartColor, "cmbChartColor");
            elementType.SelectedIndex = FindElement.Settings.ChartType ?? -1;
            elementColor.SelectedIndex = FindElement.Settings.ChartColorIndex ?? -1;
        }

        private void cmbBase_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            FindElement.Settings.DefaultSchool = cmbBase.SelectedIndex;
        }

        private void cmbServer_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            string[] url = {
               "http://mbm.medu.gov.ir/fa/",
        "http://1801.ea.medu.ir/",
        "http://1802.ea.medu.ir/",
        "http://1803.ea.medu.ir/",
        "http://1804.ea.medu.ir/",
        "http://1805.ea.medu.ir/",
        "http://1813.ea.medu.ir/",
        "http://1810.ea.medu.ir/",
        "http://1832.ea.medu.ir/",
        "http://1895.ea.medu.ir/",
        "http://1815.ea.medu.ir/",
        "http://1861.ea.medu.ir/",
        "http://1879.ea.medu.ir/",
        "http://1869.ea.medu.ir/",
        "http://1891.ea.medu.ir/",
        "http://1867.ea.medu.ir/",
        "http://1887.ea.medu.ir/",
        "http://1836.ea.medu.ir/",
        "http://1837.ea.medu.ir/",
        "http://1825.ea.medu.ir/",
        "http://1823.ea.medu.ir/",
        "http://1854.ea.medu.ir/",
        "http://1817.ea.medu.ir/",
        "http://1818.ea.medu.ir/",
        "http://1859.ea.medu.ir/",
        "http://1889.ea.medu.ir/",
        "http://1838.ea.medu.ir/",
        "http://1839.ea.medu.ir/",
        "http://1878.ea.medu.ir/",
        "http://1827.ea.medu.ir/",
        "http://1857.ea.medu.ir/",
        "http://1865.ea.medu.ir/",
        "http://1863.ea.medu.ir/",
        "http://1821.ea.medu.ir/",
        "http://1877.ea.medu.ir/",
        "http://1893.ea.medu.ir/",
        "http://1835.ea.medu.ir/",
        "http://1820.ea.medu.ir/",
        "http://1884.ea.medu.ir/",
        "http://1833.ea.medu.ir/",
        "http://wa.medu.ir/fa/",
        "http://nah1.wa.medu.ir/",
        "http://nah2.wa.medu.ir/",
        "http://anz.wa.medu.ir/",
        "http://khy.wa.medu.ir/",
        "http://chi.wa.medu.ir/",
        "http://mak.wa.medu.ir/",
        "http://sht.wa.medu.ir/",
        "http://pol.wa.medu.ir/",
        "http://chd.wa.medu.ir/",
        "http://slm.wa.medu.ir/",
        "http://mah.wa.medu.ir/",
        "http://buk.wa.medu.ir/",
        "http://mian.wa.medu.ir/",
        "http://shd.wa.medu.ir/",
        "http://tek.wa.medu.ir/",
        "http://pir.wa.medu.ir/",
        "http://sar.wa.medu.ir/",
        "http://nag.wa.medu.ir/",
        "http://osh.wa.medu.ir/portal/home.php?ocode=1000000143",
        "http://slv.wa.medu.ir/",
        "http://mar.wa.medu.ir/",
        "http://ksh.wa.medu.ir/",
        "http://som.wa.medu.ir/",
        "http://naz.wa.medu.ir/",
        "http://es.wa.medu.ir/",
        "http://arta.medu.ir/fa/",
        "http://1901.arta.medu.ir/",
        "http://1902.arta.medu.ir",
        "http://1945.arta.medu.ir",
        "http://1936.arta.medu.ir",
        "http://1942.arta.medu.ir",
        "http://1935.arta.medu.ir",
        "http://1932.arta.medu.ir",
        "http://1917.arta.medu.ir",
        "http://1920.arta.medu.ir",
        "http://1949.arta.medu.ir",
        "http://1923.arta.medu.ir",
        "http://1947.arta.medu.ir",
        "http://1926.arta.medu.ir",
        "http://1951.arta.medu.ir",
        "http://1938.arta.medu.ir",
        "http://1929.arta.medu.ir",
        "http://1914.arta.medu.ir",
        "http://1911.arta.medu.ir",
        "http://1940.arta.medu.ir",
        "http://isf73.isf.medu.ir/",
        "http://isf26.isf.medu.ir/",
        "http://isf01.isf.medu.ir/",
        "http://isf02.isf.medu.ir/",
        "http://isf03.isf.medu.ir/",
        "http://isf04.isf.medu.ir/",
        "http://isf05.isf.medu.ir/",
        "http://isf30.isf.medu.ir/",
        "http://isf87.isf.medu.ir/",
        "http://isf33.isf.medu.ir/",
        "http://isf24.isf.medu.ir/",
        "http://isf83.isf.medu.ir/",
        "http://isf43.isf.medu.ir/",
        "http://isf74.isf.medu.ir/",
        "http://isf64.isf.medu.ir/",
        "http://isf13.isf.medu.ir/",
        "http://isf17.isf.medu.ir/",
        "http://isf81.isf.medu.ir/",
        "http://isf41.isf.medu.ir/",
        "http://isf66.isf.medu.ir/",
        "http://isf50.isf.medu.ir/",
        "http://isf59.isf.medu.ir/",
        "http://isf37.isf.medu.ir/",
        "http://isf28.isf.medu.ir/",
        "http://isf85.isf.medu.ir/",
        "http://isf48.isf.medu.ir/",
        "http://isf20.isf.medu.ir/",
        "http://isf35.isf.medu.ir/",
        "http://isf39.isf.medu.ir/",
        "http://isf46.isf.medu.ir/",
        "http://isf45.isf.medu.ir/",
        "http://isf29.isf.medu.ir/",
        "http://kashanedu.ir/",
        "http://isf15.isf.medu.ir/",
        "http://isf53.isf.medu.ir/",
        "http://isf31.isf.medu.ir/",
        "http://isf75.isf.medu.ir/",
        "http://isf22.isf.medu.ir/",
        "http://isf56.isf.medu.ir/",
        "http://isf61.isf.medu.ir/",
        "http://isf79.isf.medu.ir/",
        "http://karaj1.alborz.medu.ir/",
        "http://karaj2.alborz.medu.ir/",
        "http://karaj3.alborz.medu.ir/",
        "http://karaj4.alborz.medu.ir/",
        "http://savojbolagh.alborz.medu.ir/",
        "http://nazarabad.alborz.medu.ir/",
        "http://eshtehard.alborz.medu.ir/",
        "http://taleghan.alborz.medu.ir/",
        "http://elam.medu.ir/",
        "http://abdanan.ilam.medu.ir/",
        "http://dehloran.ilam.medu.ir/",
        "http://dareshahr.ilam.medu.ir/",
        "http://mehran.ilam.medu.ir/",
        "http://malekshahi.ilam.medu.ir/",
        "http://badre.ilam.medu.ir/",
        "http://shirvan.ilam.medu.ir/",
        "http://chardavol.ilam.medu.ir/",
        "http://eyvan.ilam.medu.ir/",
        "http://zarinabad.ilam.medu.ir/",
        "http://chavar.ilam.medu.ir/",
        "http://holeilan.ilam.medu.ir/",
        "http://mosian.ilam.medu.ir/",
        "http://bushehr.medu.ir/fa/",
        "http://asaloyeh.bushehr.medu.ir/portal/home.php?ocode=64566607",
        "http://jam.bushehr.medu.ir/portal/home.php?ocode=90513509",
        "http://kangan.bushehr.medu.ir/portal/home.php?ocode=64221905",
        "http://dayer.bushehr.medu.ir/portal/home.php?ocode=64323406",
        "http://bordekhon.bushehr.medu.ir/portal/home.php?ocode=64552000",
        "http://kaki.bushehr.medu.ir/portal/home.php?ocode=64517808",
        "http://dashti.bushehr.medu.ir/portal/home.php?ocode=64130408",
        "http://delvar.bushehr.medu.ir/portal/home.php?ocode=90512803",
        "http://tangestan.bushehr.medu.ir/portal/home.php?ocode=63913404",
        "http://dashtestan.bushehr.medu.ir/portal/home.php?ocode=63643008",
        "http://saadabad.bushehr.medu.ir/portal/home.php?ocode=63720101",
        "http://abpakhsh.bushehr.medu.ir/portal/home.php?ocode=1000000841",
        "http://shabankareh.bushehr.medu.ir/portal/home.php?ocode=90512200",
        "http://rig.bushehr.medu.ir/portal/home.php?ocode=63413105",
        "http://genaveh.bushehr.medu.ir/portal/home.php?ocode=63321008",
        "http://deylam.bushehr.medu.ir/portal/home.php?ocode=63518405",
        "http://khark.bushehr.medu.ir/portal/home.php?ocode=63208405",
        "http://bu.bushehr.medu.ir/portal/home.php?ocode=63168102",
        "http://teo.medu.ir/fa/",
        "http://1217.teo.medu.ir/",
        "http://1251.teo.medu.ir/",
        "http://1281.teo.medu.ir/",
        "http://1273.teo.medu.ir/",
        "http://1292.teo.medu.ir/",
        "http://1211.teo.medu.ir/",
        "http://1220.teo.medu.ir/",
        "http://1215.teo.medu.ir/",
        "http://1294.teo.medu.ir/",
        "http://1275.teo.medu.ir/",
        "http://1296.teo.medu.ir/",
        "http://1253.teo.medu.ir/",
        "http://1285.teo.medu.ir/",
        "http://1287.teo.medu.ir/",
        "http://1283.teo.medu.ir/",
        "http://1289.teo.medu.ir/",
        "http://1271.teo.medu.ir/",
        "http://1221.teo.medu.ir/",
        "http://1272.teo.medu.ir/",
        "http://1295.teo.medu.ir/",
        "http://1255.teo.medu.ir/",
        "http://chb.medu.ir/fa/",
        "http://sh1.chb.medu.ir/",
        "http://sh2.chb.medu.ir/",
        "http://ardal.chb.medu.ir/",
        "http://farsan.chb.medu.ir/",
        "http://boroojen.chb.medu.ir/",
        "http://koohrang.chb.medu.ir/",
        "http://lordegan.chb.medu.ir/",
        "http://kiear.chb.medu.ir/",
        "http://saman.chb.medu.ir/",
        "http://ben.chb.medu.ir/",
        "http://laran.chb.medu.ir/",
        "http://gandoman.chb.medu.ir/",
        "http://felard.chb.medu.ir/",
        "http://khanmirza.chb.medu.ir/",
        "http://boldaji.chb.medu.ir/",
        "http://ashayer.chb.medu.ir/",
        "http://miankooh.chb.medu.ir/",
        "http://skh.medu.ir/fa/",
        "http://boshroye.skh.medu.ir/fa/",
        "http://birjand.skh.medu.ir/fa/",
        "http://khusf.skh.medu.ir/fa/",
        "http://darmiyan.skh.medu.ir/fa/",
        "http://dastgardan.skh.medu.ir/fa/",
        "http://zirkoh.skh.medu.ir/fa/",
        "http://sarayan.skh.medu.ir/fa/",
        "http://sarbishe.skh.medu.ir/fa/",
        "http://tabas.skh.medu.ir/fa/",
        "http://ferdos.skh.medu.ir/fa/",
        "http://qaen.skh.medu.ir/fa/",
        "http://nehbandan.skh.medu.ir/fa/",
        "http://shirvan.khn.medu.ir/portal/home.php?ocode=1000000664",
        "http://bojnord.khn.medu.ir/portal/home.php?ocode=1000000665",
        "http://esfarayen.khn.medu.ir/portal/home.php?ocode=1000000519",
        "http://razojargalan.khn.medu.ir/portal/home.php?ocode=51717405",
        "http://bamosafiabad.khn.medu.ir/portal/home.php?ocode=57690109",
        "http://jajarm.khn.medu.ir/portal/home.php?ocode=90162204",
        "http://farooj.khn.medu.ir/portal/home.php?ocode=54922401",
        "http://garme.khn.medu.ir/portal/home.php?ocode=100040074",
        "http://2126.khn.medu.ir/portal/home.php?ocode=51815406",
        "http://n1.razavi.medu.ir/",
        "http://n2.razavi.medu.ir/",
        "http://n3.razavi.medu.ir/",
        "http://n4.razavi.medu.ir/",
        "http://n5.razavi.medu.ir/",
        "http://n6.razavi.medu.ir/",
        "http://n7.razavi.medu.ir/",
        "http://es.razavi.medu.ir/",
        "http://ahmadabad.razavi.medu.ir/",
        "http://bakharz.razavi.medu.ir/",
        "http://bajestan.razavi.medu.ir/",
        "http://bardaskan.razavi.medu.ir/",
        "http://taybad.razavi.medu.ir/",
        "http://tabadkan.razavi.medu.ir/",
        "http://firoozeh.razavi.medu.ir/",
        "http://jam.razavi.medu.ir/",
        "http://heydarieh.razavi.medu.ir/",
        "http://joghatay.razavi.medu.ir/",
        "http://rokh.razavi.medu.ir/",
        "http://jovein.razavi.medu.ir/",
        "http://chenaran.razavi.medu.ir/",
        "http://khalilabad.razavi.medu.ir/",
        "http://khaf.razavi.medu.ir/",
        "http://khooshab.razavi.medu.ir/",
        "http://davarzan.razavi.medu.ir/",
        "http://daregaz.razavi.medu.ir/",
        "http://roshtkhar.razavi.medu.ir/",
        "http://razavieh.razavi.medu.ir/",
        "http://zaveh.razavi.medu.ir/",
        "http://zebarkhan.razavi.medu.ir/",
        "http://sabzevar.razavi.medu.ir/",
        "http://sarakhs.razavi.medu.ir/",
        "http://sarvelayat.razavi.medu.ir/",
        "http://sheshtamad.razavi.medu.ir/",
        "http://salehabad.razavi.medu.ir/",
        "http://torghabeh.razavi.medu.ir/",
        "http://fariman.razavi.medu.ir/",
        "http://quchan.razavi.medu.ir/",
        "http://kalat.razavi.medu.ir/",
        "http://koohsorkh.razavi.medu.ir/",
        "http://kashmar.razavi.medu.ir/",
        "http://kadkan.razavi.medu.ir/",
        "http://golbahar.razavi.medu.ir/",
        "http://gonabad.razavi.medu.ir/",
        "http://mahvelat.razavi.medu.ir/",
        "http://mianjolgeh.razavi.medu.ir/",
        "http://nokhandan.razavi.medu.ir/",
        "http://neyshabour.razavi.medu.ir/",
        "http://khouz.medu.ir/fa/",
        "http://3601.khouz.medu.ir/",
        "http://3602.khouz.medu.ir/portal/home.php?ocode=1000000298",
        "http://3603.khouz.medu.ir/portal/home.php?ocode=1000000299",
        "http://3604.khouz.medu.ir/portal/home.php?ocode=1000000300",
        "http://3688.khouz.medu.ir/portal/home.php?ocode=1000000304",
        "http://estn.khouz.medu.ir/portal/home.php?ocode=40008404",
        "http://3608.khouz.medu.ir/portal/home.php?ocode=1000000301",
        "http://3606.khouz.medu.ir/portal/home.php?ocode=1000000789",
        "http://3609.khouz.medu.ir/portal/home.php?ocode=1000000302",
        "http://3613.khouz.medu.ir/portal/home.php?ocode=1000000303",
        "http://3616.khouz.medu.ir/portal/home.php?ocode=1000000305",
        "http://3617.khouz.medu.ir/portal/home.php?ocode=1000000306",
        "http://3619.khouz.medu.ir/portal/home.php?ocode=1000000307",
        "http://3620.khouz.medu.ir/portal/home.php?ocode=1000000308",
        "http://3622.khouz.medu.ir/portal/home.php?ocode=1000000309",
        "http://3627.khouz.medu.ir/portal/home.php?ocode=1000000312",
        "http://3624.khouz.medu.ir/portal/home.php?ocode=1000000310",
        "http://3625.khouz.medu.ir/portal/home.php?ocode=1000000311",
        "http://3630.khouz.medu.ir/portal/home.php?ocode=1000000313",
        "http://3633.khouz.medu.ir/portal/home.php?ocode=1000000314",
        "http://3636.khouz.medu.ir/portal/home.php?ocode=1000000331",
        "http://3639.khouz.medu.ir/portal/home.php?ocode=1000000330",
        "http://3642.khouz.medu.ir/portal/home.php?ocode=1000000329",
        "http://3645.khouz.medu.ir/portal/home.php?ocode=1000000328",
        "http://3649.khouz.medu.ir/portal/home.php?ocode=1000000327",
        "http://3651.khouz.medu.ir/portal/home.php?ocode=1000000326",
        "http://3654.khouz.medu.ir/portal/home.php?ocode=1000000325",
        "http://3657.khouz.medu.ir/portal/home.php?ocode=1000000324",
        "http://3660.khouz.medu.ir/portal/home.php?ocode=1000000323",
        "http://3663.khouz.medu.ir/portal/home.php?ocode=1000000322",
        "http://3665.khouz.medu.ir/portal/home.php?ocode=1000000321",
        "http://3668.khouz.medu.ir/portal/home.php?ocode=1000000320",
        "http://3670.khouz.medu.ir/portal/home.php?ocode=1000000319",
        "http://3673.khouz.medu.ir/portal/home.php?ocode=1000000318",
        "http://3676.khouz.medu.ir/portal/home.php?ocode=43029206",
        "http://3677.khouz.medu.ir/portal/home.php?ocode=1000000344",
        "http://3678.khouz.medu.ir/portal/home.php?ocode=1000000317/",
        "http://3680.khouz.medu.ir/portal/home.php?ocode=43629806",
        "http://3690.khouz.medu.ir/portal/home.php?ocode=1000000316/",
        "http://3692.khouz.medu.ir/portal/home.php?ocode=1000000315",
        "http://3694.khouz.medu.ir/portal/home.php?ocode=43622909",
        "http://zanjan.medu.ir/fa/",
        "http://5743.zanjan.medu.ir",
        "http://5723.zanjan.medu.ir",
        "http://5701.zanjan.medu.ir",
        "http://5702.zanjan.medu.ir",
        "http://5711.zanjan.medu.ir",
        "http://5725.zanjan.medu.ir",
        "http://5745.zanjan.medu.ir",
        "http://5734.zanjan.medu.ir",
        "http://5712.zanjan.medu.ir",
        "http://5731.zanjan.medu.ir",
        "http://5747.zanjan.medu.ir",
        "http://5714.zanjan.medu.ir",
        "http://5705.zanjan.medu.ir",
        "http://5708.zanjan.medu.ir",
        "http://sem.semnan.medu.ir/?ocode=90600101",
        "http://shahrood.semnan.medu.ir/?ocode=90600903",
        "http://damghan.semnan.medu.ir/?ocode=90601801",
        "http://garmsar.semnan.medu.ir/?ocode=90602600",
        "http://sorkheh.semnan.medu.ir/?ocode=90602907",
        "http://mahdishahr.semnan.medu.ir/?ocode=90600607",
        "http://mayamei.semnan.medu.ir/?ocode=90601503",
        "http://aradan.semnan.medu.ir/portal/home.php?ocode=1000000790",
        "http://amirabad.semnan.medu.ir/?ocode=90602209",
        "http://bastam.semnan.medu.ir/?ocode=90601101",
        "http://beyarjomand.semnan.medu.ir/?ocode=90602706",
        "http://4901.sb.medu.ir/fa/",
        "http://4902.sb.medu.ir/fa/",
        "http://caspian.medu.ir/fa/",
        "http://4617.caspian.medu.ir/",
        "http://4620.caspian.medu.ir/",
        "http://4628.caspian.medu.ir/",
        "http://4629.caspian.medu.ir/",
        "http://4630.caspian.medu.ir/",
        "http://4633.caspian.medu.ir/",
        "http://4636.caspian.medu.ir/",
        "http://4639.caspian.medu.ir/",
        "http://4640.caspian.medu.ir/",
        "http://4641.caspian.medu.ir/",
        "http://4643.caspian.medu.ir/",
        "http://4645.caspian.medu.ir/",
        "http://4647.caspian.medu.ir/",
        "http://4649.caspian.medu.ir/",
        "http://n1.qom.medu.ir/",
        "http://n2.qom.medu.ir/",
        "http://n3.qom.medu.ir/",
        "http://n4.qom.medu.ir/",
        "http://kahak.qom.medu.ir/",
        "http://jafarabad.qom.medu.ir/",
        "http://khalajestan.qom.medu.ir/",
        "http://kurd.medu.ir/fa/",
        "http://san1.kurd.medu.ir/",
        "http://san2.kurd.medu.ir/",
        "http://sgh.kurd.medu.ir/",
        "http://bnh.kurd.medu.ir/",
        "http://mar.kurd.medu.ir/",
        "http://ghr.kurd.medu.ir/",
        "http://bij.kurd.medu.ir/",
        "http://dvn.kurd.medu.ir/",
        "http://kam.kurd.medu.ir/",
        "http://dhg.kurd.medu.ir/",
        "http://sar.kurd.medu.ir/",
        "http://sri.kurd.medu.ir/",
        "http://mch.kurd.medu.ir/",
        "http://krn.kurd.medu.ir/",
        "http://ziv.kurd.medu.ir/",
        "http://klt.kurd.medu.ir/",
        "http://kerman.medu.ir/fa/",
        "http://est.kerman.medu.ir/",
        "http://ash.kerman.medu.ir/",
        "http://orz.kerman.medu.ir/",
        "http://anr.kerman.medu.ir/",
        "http://bft.kerman.medu.ir/",
        "http://brd.kerman.medu.ir/",
        "http://bam.kerman.medu.ir/",
        "http://jrf.kerman.medu.ir/",
        "http://chr.kerman.medu.ir/",
        "http://rbr.kerman.medu.ir/",
        "http://rvr.kerman.medu.ir/",
        "http://ryn.kerman.medu.ir/",
        "http://rfs.kerman.medu.ir/",
        "http://rud.kerman.medu.ir/",
        "http://rgn.kerman.medu.ir/",
        "http://zrn.kerman.medu.ir/",
        "http://srn.kerman.medu.ir/",
        "http://shd.kerman.medu.ir/",
        "http://shr.kerman.medu.ir/",
        "http://anb.kerman.medu.ir/",
        "http://frb.kerman.medu.ir/",
        "http://fhr.kerman.medu.ir/",
        "http://gln.kerman.medu.ir/",
        "http://ksh.kerman.medu.ir/",
        "http://kuh.kerman.medu.ir/",
        "http://khn.kerman.medu.ir/",
        "http://glb.kerman.medu.ir/",
        "http://mhn.kerman.medu.ir/",
        "http://mnj.kerman.medu.ir/",
        "http://kn1.kerman.medu.ir/",
        "http://kn2.kerman.medu.ir/",
        "http://nrm.kerman.medu.ir/",
        "http://nog.kerman.medu.ir/",
        "http://kermanshah.medu.ir/fa/",
        "http://nah1.kermanshah.medu.ir/",
        "http://nah2.kermanshah.medu.ir/",
        "http://nah3.kermanshah.medu.ir/",
        "http://eslamabadgharb.kermanshah.medu.ir/",
        "http://bayangan.kermanshah.medu.ir/",
        "http://bisotun.kermanshah.medu.ir/",
        "http://paveh.kermanshah.medu.ir/",
        "http://salas.kermanshah.medu.ir/",
        "http://javanrud.kermanshah.medu.ir/",
        "http://homail.kermanshah.medu.ir/",
        "http://dalahoo.kermanshah.medu.ir/",
        "http://dinevar.kermanshah.medu.ir/",
        "http://ravansar.kermanshah.medu.ir/",
        "http://sarpolzahab.kermanshah.medu.ir/",
        "http://sonqor.kermanshah.medu.ir/",
        "http://sahneh.kermanshah.medu.ir/",
        "http://qasrshirin.kermanshah.medu.ir/",
        "http://kangavar.kermanshah.medu.ir/",
        "http://govaver.kermanshah.medu.ir/",
        "http://gahvareh.kermanshah.medu.ir/",
        "http://gilangharb.kermanshah.medu.ir/",
        "http://mahidasht.kermanshah.medu.ir/",
        "http://nosoud.kermanshah.medu.ir/",
        "http://harsin.kermanshah.medu.ir/",
        "http://kb.medu.ir/fa/",
        "http://4259.kb.medu.ir/",
        "http://4269.kb.medu.ir/",
        "http://4280.kb.medu.ir/",
        "http://4288.kb.medu.ir/",
        "http://4282.kb.medu.ir/",
        "http://4278.kb.medu.ir/",
        "http://4277.kb.medu.ir/",
        "http://4275.kb.medu.ir/",
        "http://4266.kb.medu.ir/",
        "http://4264.kb.medu.ir/",
        "http://4271.kb.medu.ir/",
        "http://4263.kb.medu.ir/",
        "http://4261.kb.medu.ir/",
        "http://golestan.medu.ir/fa/",
        "http://azadshahr.golestan.medu.ir/",
        "http://aghghala.golestan.medu.ir/",
        "http://bandartorkman.golestan.medu.ir/",
        "http://bandargaz.golestan.medu.ir/",
        "http://ramian.golestan.medu.ir/",
        "http://aliabad.golestan.medu.ir/",
        "http://kordkuy.golestan.medu.ir/",
        "http://kalaleh.golestan.medu.ir/",
        "http://galikesh.golestan.medu.ir/",
        "http://gorgan.golestan.medu.ir/",
        "http://gomishan.golestan.medu.ir/",
        "http://gonbad.golestan.medu.ir/",
        "http://maraveh.golestan.medu.ir/",
        "http://minoodasht.golestan.medu.ir/",
        "http://guilan.medu.ir/fa/",
        "http://3701.gilan.medu.ir/",
        "http://3702.gilan.medu.ir/",
        "http://3764.gilan.medu.ir/",
        "http://3750.gilan.medu.ir/",
        "http://3770.gilan.medu.ir/",
        "http://3728.gilan.medu.ir/",
        "http://3716.gilan.medu.ir/",
        "http://3733.gilan.medu.ir/",
        "http://3747.gilan.medu.ir/",
        "http://3774.gilan.medu.ir/",
        "http://3707.gilan.medu.ir/",
        "http://3706.gilan.medu.ir/",
        "http://3724.gilan.medu.ir/",
        "http://3768.gilan.medu.ir/",
        "http://3730.gilan.medu.ir/",
        "http://3735.gilan.medu.ir/",
        "http://3759.gilan.medu.ir/",
        "http://3772.gilan.medu.ir/",
        "http://3725.gilan.medu.ir/",
        "http://3713.gilan.medu.ir/",
        "http://3722.gilan.medu.ir/",
        "http://3742.gilan.medu.ir/",
        "http://3745.gilan.medu.ir/",
        "http://3761.gilan.medu.ir/",
        "http://3740.gilan.medu.ir/",
        "http://3727.gilan.medu.ir/",
        "http://3708.gilan.medu.ir/",
        "http://3766.gilan.medu.ir/",
        "http://3753.gilan.medu.ir/",
        "http://3719.gilan.medu.ir/",
        "http://3711.gilan.medu.ir/",
        "http://3756.gilan.medu.ir/",
        "http://3737.gilan.medu.ir/",
        "http://lorestan.medu.ir/fa/",
        "http://azn.lorestan.medu.ir/fa/",
        "http://est.lorestan.medu.ir/fa/",
        "http://als.lorestan.medu.ir/",
        "http://alg.lorestan.medu.ir/",
        "http://bru.lorestan.medu.ir/",
        "http://byr.lorestan.medu.ir/",
        "http://pop.lorestan.medu.ir/fa/",
        "http://pol.lorestan.medu.ir/fa/",
        "http://chg.lorestan.medu.ir/fa/",
        "http://kh1.lorestan.medu.ir/",
        "http://dur.lorestan.medu.ir/",
        "http://rom.lorestan.medu.ir/fa/",
        "http://zgh.lorestan.medu.ir/",
        "http://slk.lorestan.medu.ir/",
        "http://tar.lorestan.medu.ir/",
        "http://zaz.lorestan.medu.ir/fa/",
        "http://ash.lorestan.medu.ir/fa/",
        "http://kak.lorestan.medu.ir/",
        "http://koh.lorestan.medu.ir/",
        "http://mam.lorestan.medu.ir/fa/",
        "http://nor.lorestan.medu.ir/",
        "http://vey.lorestan.medu.ir/fa/",
        "http://kh2.lorestan.medu.ir/fa/",
        "http://mazand.medu.ir/fa/",
        "http://simorgh.mazand.medu.ir/fa/",
        "http://amol.mazand.medu.ir/fa/",
        "http://babolsar.mazand.medu.ir/fa/",
        "http://tonekabon.mazand.medu.ir/fa/",
        "http://chalus.mazand.medu.ir/fa/",
        "http://shirgah.mazand.medu.ir/fa/?ocode=100038255",
        "http://sari1.mazand.medu.ir/fa/",
        "http://abbasabad.mazand.medu.ir/fa/",
        "http://qaemshahr.mazand.medu.ir/fa/",
        "http://nur.mazand.medu.ir/fa/",
        "http://galugah.mazand.medu.ir/fa/",
        "http://haraz.mazand.medu.ir/fa/",
        "http://chamestan.mazand.medu.ir/fa/",
        "http://miandorod.mazand.medu.ir/fa/",
        "http://bpgharbi.mazand.medu.ir/fa/",
        "http://kojoor.mazand.medu.ir/fa/",
        "http://chardangeh.mazand.medu.ir/fa/",
        "http://dodangeh.mazand.medu.ir/fa/",
        "http://sari2.mazand.medu.ir/fa/",
        "http://babol.mazand.medu.ir/fa/",
        "http://behshahr.mazand.medu.ir/fa/",
        "http://juybar.mazand.medu.ir/fa/",
        "http://ramsar.mazand.medu.ir/fa/",
        "http://larijan.mazand.medu.ir/fa/",
        "http://savadkuh.mazand.medu.ir/fa/",
        "http://fkenar.mazand.medu.ir/fa/",
        "http://nowshahr.mazand.medu.ir/fa/",
        "http://neka.mazand.medu.ir/fa/",
        "http://bahnemir.mazand.medu.ir/fa/",
        "http://bpsharghi.mazand.medu.ir/fa/",
        "http://kelardasht.mazand.medu.ir/fa/",
        "http://baladeh.mazand.medu.ir/fa/",
        "http://markazi.medu.ir/fa/",
        "http://mahallat.markazi.medu.ir/portal/home.php?ocode=17209102",
        "http://nobaran.markazi.medu.ir/portal/home.php?ocode=17009505",
        "http://farahan.markazi.medu.ir/portal/home.php?ocode=16709800",
        "http://komijan.markazi.medu.ir/portal/home.php?ocode=1000000475",
        "http://shazand.markazi.medu.ir/portal/home.php?ocode=90158008",
        "http://sarband.markazi.medu.ir/portal/home.php?ocode=17520208",
        "http://saveh.markazi.medu.ir/portal/home.php?ocode=16825007",
        "http://zarand.markazi.medu.ir/portal/home.php?ocode=16910408",
        "http://delijan.markazi.medu.ir/portal/home.php?ocode=16314609",
        "http://khondab.markazi.medu.ir/portal/home.php?ocode=16416702",
        "http://khomein.markazi.medu.ir/portal/home.php?ocode=17129100",
        "http://tafresh.markazi.medu.ir/portal/home.php?ocode=16610203",
        "http://ashtiyan.markazi.medu.ir/portal/home.php?ocode=16508006",
        "http://arak1.markazi.medu.ir/portal/home.php?ocode=16133600",
        "http://arak2.markazi.medu.ir/portal/home.php?ocode=16221108",
        "http://hormozgan.medu.ir/fa/",
        "http://bastak.hormozgan.medu.ir/",
        "http://bashagard.hormozgan.medu.ir/",
        "http://khamir.hormozgan.medu.ir/",
        "http://bndlengeh.hormozgan.medu.ir/",
        "http://nahiye1.hormozgan.medu.ir/",
        "http://nahiye2.hormozgan.medu.ir/",
        "http://parsiyan.hormozgan.medu.ir/",
        "http://jask.hormozgan.medu.ir/",
        "http://jenah.hormozgan.medu.ir/",
        "http://hajiabad.hormozgan.medu.ir/",
        "http://roodan.hormozgan.medu.ir/",
        "http://roudkhaneh.hormozgan.medu.ir/",
        "http://senderk.hormozgan.medu.ir/",
        "http://sirik.hormozgan.medu.ir/",
        "http://shahab.hormozgan.medu.ir/",
        "http://fin.hormozgan.medu.ir/",
        "http://qeshm.hormozgan.medu.ir/",
        "http://kish.hormozgan.medu.ir/",
        "http://minab.hormozgan.medu.ir/",
        "http://hormoz.hormozgan.medu.ir/",
        "http://hamedan.medu.ir/fa/",
        "http://n1.hamedan.medu.ir/",
        "http://n2.hamedan.medu.ir/",
        "http://asd.hamedan.medu.ir/",
        "http://raz.hamedan.medu.ir/",
        "http://bah.hamedan.medu.ir/",
        "http://kab.hamedan.medu.ir/",
        "http://mal.hamedan.medu.ir/",
        "http://toy.hamedan.medu.ir/",
        "http://nah.hamedan.medu.ir/",
        "http://fam.hamedan.medu.ir/",
        "http://gah.hamedan.medu.ir/",
        "http://sar.hamedan.medu.ir/",
        "http://samn.hamedan.medu.ir/",
        "http://khz.hamedan.medu.ir/",
        "http://jkr.hamedan.medu.ir/",
        "http://gol.hamedan.medu.ir/",
        "http://ghr.hamedan.medu.ir/",
        "http://ghl.hamedan.medu.ir/",
        "http://laj.hamedan.medu.ir/",
        "http://yazd.medu.ir/fa/"
};
            FindElement.Settings.DefaultServer = url[cmbServer.SelectedIndex].ToString();
        }

        private void loadServers()
        {
            string[] city = new string[]{
                "امور بین الملل مدارس خارج کشور",
        "آذربایجان شرقی← ناحیه 1 تبریز",
        "آذربایجان شرقی← ناحیه 2 تبریز",
        "آذربایجان شرقی← ناحیه 3 تبریز",
        "آذربایجان شرقی← ناحیه 4 تبریز",
        "آذربایجان شرقی← ناحیه 5 تبریز",
        "آذربایجان شرقی← آذرشهر",
        "آذربایجان شرقی← اسکو",
        "آذربایجان شرقی← اهر",
        "آذربایجان شرقی← ایلخچی",
        "آذربایجان شرقی← بستان آباد",
        "آذربایجان شرقی← بناب",
        "آذربایجان شرقی← ترکمنچای",
        "آذربایجان شرقی← تسوج",
        "آذربایجان شرقی← تیکمه داش",
        "آذربایجان شرقی← جلفا",
        "آذربایجان شرقی← چاراویماق",
        "آذربایجان شرقی← خاروانا",
        "آذربایجان شرقی← خداآفرین",
        "آذربایجان شرقی← خسروشاه",
        "آذربایجان شرقی← خواجه",
        "آذربایجان شرقی← سراب",
        "آذربایجان شرقی← شبستر",
        "آذربایجان شرقی← صوفیان",
        "آذربایجان شرقی← عجب شیر",
        "آذربایجان شرقی← عشایر",
        "آذربایجان شرقی← کاغذکنان",
        "آذربایجان شرقی← کلیبر",
        "آذربایجان شرقی← کندوان",
        "آذربایجان شرقی← گوکان",
        "آذربایجان شرقی← مراغه",
        "آذربایجان شرقی← مرند",
        "آذربایجان شرقی← ملکان",
        "آذربایجان شرقی← مهربان",
        "آذربایجان شرقی← میانه",
        "آذربایجان شرقی← نظرکهریز",
        "آذربایجان شرقی← ورزقان",
        "آذربایجان شرقی← هریس",
        "آذربایجان شرقی← هشترود",
        "آذربایجان شرقی← هوراند",
        "آذربایجان غربی← آذربایجان غربی",
        "آذربایجان غربی← نایحه 1 ارومیه",
        "آذربایجان غربی← ناحیه 2 ارومیه",
        "آذربایجان غربی← انزل",
        "آذربایجان غربی← خوی",
        "آذربایجان غربی← چایپاره",
        "آذربایجان غربی← ماکو",
        "آذربایجان غربی← شوط",
        "آذربایجان غربی← پلدشت",
        "آذربایجان غربی← چالدران",
        "آذربایجان غربی← سلماس",
        "آذربایجان غربی← مهاباد",
        "آذربایجان غربی← بوکان",
        "آذربایجان غربی← میاندوآب",
        "آذربایجان غربی← شاهین دژ",
        "آذربایجان غربی← تکاب",
        "آذربایجان غربی← پیرانشهر",
        "آذربایجان غربی← سردشت",
        "آذربایجان غربی← نقده",
        "آذربایجان غربی← اشنویه",
        "آذربایجان غربی← سیلوانا",
        "آذربایجان غربی← مرحمت آباد",
        "آذربایجان غربی← کشاورز",
        "آذربایجان غربی← صومای",
        "آذربایجان غربی← نازلو",
        "آذربایجان غربی← آموزش و پرورش استثنایی",
        "اردبیل← اردبیل",
        "اردبیل← ناحیه1",
        "اردبیل← ناحیه2",
        "اردبیل← ارشق",
        "اردبیل← اصلاندوز",
        "اردبیل← انگوت",
        "اردبیل← بیله سوار",
        "اردبیل← پارس آباد",
        "اردبیل← خلخال",
        "اردبیل← خورش رستم",
        "اردبیل← سرعین",
        "اردبیل← شاهرود",
        "اردبیل← جعفرآباد",
        "اردبیل← کوثر",
        "اردبیل← لاهرود",
        "اردبیل← مشگین شهر",
        "اردبیل← گرمی",
        "اردبیل ← نمین",
        "اردبیل← نیر",
        "اردبیل← هیر",
        "اصفهان← آران و بیدگل",
        "اصفهان← اردستان",
        "اصفهان← اصفهان ناحیه 1",
        "اصفهان← اصفهان ناحیه 2",
        "اصفهان← اصفهان ناحیه 3",
        "اصفهان← اصفهان ناحیه 4",
        "اصفهان← اصفهان ناحیه 5",
        "اصفهان← اصفهان ناحیه 6",
        "اصفهان← امامزاده",
        "اصفهان← باغبهادران",
        "اصفهان← برخوار",
        "اصفهان← بن رود",
        "اصفهان← بوئین و میاندشت",
        "اصفهان← پیربکران",
        "اصفهان← تیران وکرون",
        "اصفهان← جرقویه سفلی",
        "اصفهان← جرقویه علیا",
        "اصفهان← جلگه",
        "اصفهان← چادگان",
        "اصفهان← خمینی شهر",
        "اصفهان← خوانسار",
        "اصفهان← خوروبیانک",
        "اصفهان← دهاقان",
        "اصفهان← زرین شهر",
        "اصفهان← زواره",
        "اصفهان← سمیرم",
        "اصفهان← شاهین شهر",
        "اصفهان← شهرضا",
        "اصفهان← فریدن",
        "اصفهان← فریدونشهر",
        "اصفهان← فلاورجان",
        "اصفهان← فولادشهر",
        "اصفهان← کاشان",
        "اصفهان← کوهپایه",
        "اصفهان← گلپایگان",
        "اصفهان← مبارکه",
        "اصفهان← مهردشت",
        "اصفهان← میمه",
        "اصفهان← نائین",
        "اصفهان← نجف آباد",
        "اصفهان← نطنز",
        "البرز← ناحیه 1",
        "البرز← ناحیه 2",
        "البرز← ناحیه 3",
        "البرز← ناحیه 4",
        "البرز← ساوجبلاغ",
        "البرز← نظرآباد",
        "البرز← اشتهارد",
        "البرز← طالقان",
        "ایلام← ایلام",
        "ایلام← آبدانان",
        "ایلام← دهلران",
        "ایلام← دره شهر",
        "ایلام← مهران",
        "ایلام← ملکشاهی",
        "ایلام← بدره",
        "ایلام← سیروان",
        "ایلام← چرداول",
        "ایلام← ایوان",
        "ایلام← زرین آباد",
        "ایلام← چوار",
        "ایلام← هلیان",
        "ایلام← موسیان",
        "بوشهر← بوشهر",
        "بوشهر← عسلویه",
        "بوشهر← جم",
        "بوشهر← کنگان",
        "بوشهر← دیر",
        "بوشهر← بردخون",
        "بوشهر← کاکی",
        "بوشهر← دشتی",
        "بوشهر← دلوار",
        "بوشهر← تنگستان",
        "بوشهر← دشتستان",
        "بوشهر← سعدآباد",
        "بوشهر← آبپخش",
        "بوشهر← شبانکاره",
        "بوشهر← ریک",
        "بوشهر← کنگاوه",
        "بوشهر← دیلم",
        "بوشهر← خارک",
        "بوشهر← بوشهر",
        "تهران← تهران",
        "تهران← شهر قدس",
        "تهران← شهریار",
        "تهران← دماوند",
        "تهران← جوادآباد",
        "تهران← اسلامشهر",
        "تهران← فشافویه",
        "تهران← شهر ری یک",
        "تهران← کهریزک",
        "تهران← بهارستان یک",
        "تهران← پاکدشت",
        "تهران← پردیس",
        "تهران← ملارد",
        "تهران← فیروزکوه",
        "تهران← پیشوا",
        "تهران← رودهن",
        "تهران← چهاردانگه",
        "تهران← ورامین",
        "تهران← شهر ری دو",
        "تهران← قرچک",
        "تهران← بهارستان دو",
        "تهران← رباط کریم",
        "چهارمحال بختیاری← چهارمحال بختیاری",
        "چهارمحال بختیاری← ناحیه 1 شهرکرد",
        "چهارمحال بختیاری← ناحیه 2 شهرکرد",
        "چهارمحال بختیاری← اردل",
        "چهارمحال بختیاری← فارسان",
        "چهارمحال بختیاری← بروجن",
        "چهارمحال بختیاری← کوهرنگ",
        "چهارمحال بختیاری← لردگان",
        "چهارمحال بختیاری← کیار",
        "چهارمحال بختیاری← سامان",
        "چهارمحال بختیاری← بن",
        "چهارمحال بختیاری← لاران",
        "چهارمحال بختیاری← گندمان",
        "چهارمحال بختیاری← فلارد",
        "چهارمحال بختیاری← خانمیرزا",
        "چهارمحال بختیاری← بلداجی",
        "چهارمحال بختیاری← عشایر",
        "چهارمحال بختیاری← میانکوه",
        "خراسان جنوبی← خراسان جنوبی",
        "خراسان جنوبی← بشرویه",
        "خراسان جنوبی← بیرجند",
        "خراسان جنوبی← خوسف",
        "خراسان جنوبی← درمیان",
        "خراسان جنوبی← دستگردان",
        "خراسان جنوبی← زیرکوه",
        "خراسان جنوبی← سرایان",
        "خراسان جنوبی← سرپیشه",
        "خراسان جنوبی← طبس",
        "خراسان جنوبی← فردوس",
        "خراسان جنوبی← قاینات",
        "خراسان جنوبی← نهبندان",
        "خراسان شمالی← شیروان",
        "خراسان شمالی← بجنورد",
        "خراسان شمالی← اسفراین",
        "خراسان شمالی← رازوجرگلان",
        "خراسان شمالی← بام و صفی آباد",
        "خراسان شمالی← جاجرم",
        "خراسان شمالی← فاروج",
        "خراسان شمالی← گرمه",
        "خراسان شمالی← مانه و سملقان",
        "خراسان رضوی← ناحیه یک",
        "خراسان رضوی← ناحیه دو",
        "خراسان رضوی← ناحیه سه",
        "خراسان رضوی← ناحیه چهار",
        "خراسان رضوی← ناحیه پنج",
        "خراسان رضوی← ناحیه شش",
        "خراسان رضوی← ناحیه هفت",
        "خراسان رضوی← استثنائی",
        "خراسان رضوی← احمدآباد",
        "خراسان رضوی← باخرز",
        "خراسان رضوی← بجستان",
        "خراسان رضوی← بردسکن",
        "خراسان رضوی← تایباد",
        "خراسان رضوی← تبادکان",
        "خراسان رضوی← تحت جلگه",
        "خراسان رضوی← تربت جام",
        "خراسان رضوی← تربت حیدریه",
        "خراسان رضوی← جغتای",
        "خراسان رضوی← جلگه رخ",
        "خراسان رضوی← جوین",
        "خراسان رضوی← چناران",
        "خراسان رضوی← خلیل آباد",
        "خراسان رضوی← خواف",
        "خراسان رضوی← خوشاب",
        "خراسان رضوی← داورزن",
        "خراسان رضوی← درگز",
        "خراسان رضوی← رشتخوار",
        "خراسان رضوی← رضویه",
        "خراسان رضوی← زاوه",
        "خراسان رضوی← زبرخان",
        "خراسان رضوی← سبزوار",
        "خراسان رضوی← سرخس",
        "خراسان رضوی← سرولایت",
        "خراسان رضوی← ششتمد",
        "خراسان رضوی← صالح آباد",
        "خراسان رضوی← طرقبه",
        "خراسان رضوی← فریمان",
        "خراسان رضوی← قوچان",
        "خراسان رضوی← کلات",
        "خراسان رضوی← کوهسرخ",
        "خراسان رضوی← کاشمر",
        "خراسان رضوی← کدکن",
        "خراسان رضوی← گلبهار",
        "خراسان رضوی← گناباد",
        "خراسان رضوی← مه ولات",
        "خراسان رضوی← میان جلگه",
        "خراسان رضوی← نوخندان",
        "خراسان رضوی← نیشابور",
        "خوزستان← خوزستان",
        "خوزستان← ناحیه 1",
        "خوزستان← ناحیه 2",
        "خوزستان← ناحیه 3",
        "خوزستان← ناحیه 4",
        "خوزستان← عشایری خوزستان",
        "خوزستان← استثنایی",
        "خوزستان← باوی",
        "خوزستان← کارون",
        "خوزستان← آبادان",
        "خوزستان← اروندکنار",
        "خوزستان← ایذه",
        "خوزستان← دهدز",
        "خوزستان← باغملک",
        "خوزستان← صیدون",
        "خوزستان← بهبهان",
        "خوزستان← خرمشهر",
        "خوزستان← زیدون",
        "خوزستان← آغاجاری",
        "خوزستان← دزفول",
        "خوزستان← شوش",
        "خوزستان← اندیمشک",
        "خوزستان← دشت آزادگان",
        "خوزستان← بستان",
        "خوزستان← هویزه",
        "خوزستان← رامهرمز",
        "خوزستان← رامشیر",
        "خوزستان← شادگان",
        "خوزستان← بندرماهشهر",
        "خوزستان← بندر امام خمینی",
        "خوزستان← هندیجان",
        "خوزستان← مسجد سلیمان",
        "خوزستان← لالی",
        "خوزستان← هفتکل",
        "خوزستان← شوشتر",
        "خوزستان← گتوند",
        "خوزستان← امیدیه",
        "خوزستان← اتدیکا",
        "خوزستان← سردشت",
        "خوزستان← الوار گرمسیری",
        "خوزستان← شاوور",
        "خوزستان← جمیدیه",
        "زنجان← زنجان",
        "زنجان← بزینه رود",
        "زنجان← خدابنده",
        "زنجان← ناحیه 1 زنجان",
        "زنجان← ناحیه 2 زنجان",
        "زنجان← ابهر",
        "زنجان← افشار",
        "زنجان← انگوران",
        "زنجان← ایجرود",
        "زنجان← خرمدره",
        "زنجان← زنجان رود",
        "زنجان← سجاس رود",
        "زنجان← سلطانیه",
        "زنجان← طارم",
        "زنجان← ماهنشان",
        "سمنان← سمنان",
        "سمنان← شاهرود",
        "سمنان← دامغان",
        "سمنان← گرمسار",
        "سمنان← سرخه",
        "سمنان← مهدی شهر",
        "سمنان← میامی",
        "سمنان← آرادان",
        "سمنان← امیرآباد",
        "سمنان← بسطام",
        "سمنان← بیارجمند",
        "سیستان و بلوچستان← ناحیه 1 زاهدان",
        "سیستان و بلوچستان← ناحیه 1 زاهدان",
        "قزوین← قزوین",
        "قزوین← تاکستان",
        "قزوین← ضیاآباد",
        "قزوین← ناحیه یک",
        "قزوین← ناحیه دو",
        "قزوین← آبیک",
        "قزوین← آوج",
        "قزوین← بویین زهرا",
        "قزوین← الموت شرقی",
        "قزوین← الموت غربی",
        "قزوین← طارم سفلی",
        "قزوین← خرمدشت",
        "قزوین← البرز",
        "قزوین← اسفرورین",
        "قزوین← شال",
        "قم← ناحیه یک",
        "قم← ناحیه دو",
        "قم← ناحیه سه",
        "قم← ناحیه چهار",
        "قم← کهک",
        "قم← جعفرآباد",
        "قم← خلجستان",
        "کردستان← کردستان",
        "کردستان← ناحیه یک سنندج",
        "کردستان← ناحیه دو سنندج",
        "کردستان← سقز",
        "کردستان← بانه",
        "کردستان← مریوان",
        "کردستان← قروه",
        "کردستان← بیجار",
        "کردستان← دیواندره",
        "کردستان← کامیاران",
        "کردستان← دهگلان",
        "کردستان← سروآباد",
        "کردستان← سریش آباد",
        "کردستان← موچش",
        "کردستان← کرانی",
        "کردستان← زیویه",
        "کردستان← کلاترزان",
        "کرمان← کرمان",
        "کرمان← استثنایی",
        "کرمان← عشایری",
        "کرمان← ارزوئیه",
        "کرمان← انار",
        "کرمان← بافت",
        "کرمان← بردسیر",
        "کرمان← بم",
        "کرمان← جیرفت",
        "کرمان← چترود",
        "کرمان← رابر",
        "کرمان← راور",
        "کرمان← راین",
        "کرمان← رفسنجان",
        "کرمان← رودبار جنوب",
        "کرمان← ریگان",
        "کرمان← زرند",
        "کرمان← سیرجان",
        "کرمان← شهداد",
        "کرمان← شهربابک",
        "کرمان← عنبرآباد",
        "کرمان← فاریاب",
        "کرمان← فهرج",
        "کرمان← قلعه گنج",
        "کرمان← کشکوئیه",
        "کرمان← کوهبنان",
        "کرمان← کهنوج",
        "کرمان← گلباف",
        "کرمان← ماهان",
        "کرمان← منوجان",
        "کرمان← ناحیه یک",
        "کرمان← ناحیه دو",
        "کرمان← نرماشیر",
        "کرمان← نوق",
        "کرمانشاه← کرمانشاه",
        "کرمانشاه← ناحیه یک",
        "کرمانشاه← ناحیه دو",
        "کرمانشاه← ناحیه سه",
        "کرمانشاه← اسلام آباد غرب",
        "کرمانشاه← باینگان",
        "کرمانشاه← بیستون",
        "کرمانشاه← پاوه",
        "کرمانشاه← ثلاث باباجانی",
        "کرمانشاه← جوانرود",
        "کرمانشاه← حمیل",
        "کرمانشاه← دالاهو",
        "کرمانشاه← دینور",
        "کرمانشاه← روانسر",
        "کرمانشاه← سرپل ذهاب",
        "کرمانشاه← سنقر کلیایی",
        "کرمانشاه← صحنه",
        "کرمانشاه← قصر شیرین",
        "کرمانشاه← کنگاور",
        "کرمانشاه← گواور",
        "کرمانشاه← گهواره",
        "کرمانشاه← گیلانغرب",
        "کرمانشاه← ماهیدشت",
        "کرمانشاه← نوسود",
        "کرمانشاه← هرسین",
        "کهگیلویه و بویراحمد← کهگیلویه و بویراحمد",
        "کهگیلویه و بویراحمد← بویراحمد",
        "کهگیلویه و بویراحمد← بهمئی",
        "کهگیلویه و بویراحمد← لوداب",
        "کهگیلویه و بویراحمد← عشایر",
        "کهگیلویه و بویراحمد← دیشموک",
        "کهگیلویه و بویراحمد← مارگون",
        "کهگیلویه و بویراحمد← چاروسا",
        "کهگیلویه و بویراحمد← باشت",
        "کهگیلویه و بویراحمد← چرام",
        "کهگیلویه و بویراحمد← لنده",
        "کهگیلویه و بویراحمد← گچساران",
        "کهگیلویه و بویراحمد← دهدشت",
        "کهگیلویه و بویراحمد← دنا",
        "گلستان← گلستان",
        "گلستان← آزادشهر",
        "گلستان← آق قلا",
        "گلستان← بندرترکمن",
        "گلستان← بندرگز",
        "گلستان← رامیان",
        "گلستان← علی آبادکتول",
        "گلستان← کردکوی",
        "گلستان← کلاله",
        "گلستان← گالیکش",
        "گلستان← گرگان",
        "گلستان← گمیشان",
        "گلستان← گنبد کاووس",
        "گلستان← مراوه تپه",
        "گلستان← مینودشت",
        "گیلان← گیلان",
        "گیلان← ناحیه 1",
        "گیلان← ناحیه 2",
        "گیلان← استارا",
        "گیلان← استانه",
        "گیلان← اطاقور",
        "گیلان← املش",
        "گیلان← انزلی",
        "گیلان← تالش",
        "گیلان← تولمات",
        "گیلان← چابکسر",
        "گیلان← خشکبیجار",
        "گیلان← خمام",
        "گیلان← دیلمان",
        "گیلان← رحمت آباد",
        "گیلان← رحیم آباد",
        "گیلان← رضوانشهر",
        "گیلان← رودبار",
        "گیلان← رودبنه",
        "گیلان← رودسر",
        "گیلان← سنگر",
        "گیلان← سیاهکل",
        "گیلان← شفت",
        "گیلان← صومعه سرا",
        "گیلان← عمارلو",
        "گیلان← فومن",
        "گیلان← کلاچای",
        "گیلان← کوچصفهان",
        "گیلان← کومله",
        "گیلان← کیاشهر",
        "گیلان← لاهیجان",
        "گیلان← لشت نشا",
        "گیلان← لنگرود",
        "گیلان← ماسال",
        "لرستان← لرستان",
        "لرستان← ازنا",
        "لرستان← استثنایی",
        "لرستان← الشتر",
        "لرستان← الیگودرز",
        "لرستان← بروجرد",
        "لرستان← پیرانشهر",
        "لرستان← پاپی",
        "لرستان← پلدختر",
        "لرستان← چگنی",
        "لرستان← ناحیه یک خرم آباد",
        "لرستان← دورود",
        "لرستان← رومشکان",
        "لرستان← زاغه",
        "لرستان← سیلاخور",
        "لرستان← طرحان",
        "لرستان← ززوماهرو",
        "لرستان← عشایری",
        "لرستان← کاکاوند",
        "لرستان← کوهدشت",
        "لرستان← معمولان",
        "لرستان← نورآباد",
        "لرستان← ویسیان",
        "لرستان← ناحیه دو خرم آباد",
        "مازندران← مازندران",
        "مازندران← سیمرغ",
        "مازندران← آمل",
        "مازندران← بابلسر",
        "مازندران← تنکابن",
        "مازندران← چالوس",
        "مازندران← شیرگاه",
        "مازندران← ساری 1",
        "مازندران← عباس آباد",
        "مازندران← قائمشهر",
        "مازندران← نور",
        "مازندران← گلوگاه",
        "مازندران← محمودآباد",
        "مازندران← چمستان",
        "مازندران← میانرود",
        "مازندران← بندپی غربی",
        "مازندران← کجور",
        "مازندران← چهاردانگه",
        "مازندران← دودانگه",
        "مازندران← ساری 2",
        "مازندران← بابل",
        "مازندران← بهشهر",
        "مازندران← جویبار",
        "مازندران← رامسر",
        "مازندران← لاریجان",
        "مازندران← سوادکوه",
        "مازندران← فریدونکنار",
        "مازندران← نوشهر",
        "مازندران← نکا",
        "مازندران← بهنمیر",
        "مازندران← بندپی شرقی",
        "مازندران← کلاردشت",
        "مازندران← بلده",
        "مرکزی← مرکزی",
        "مرکزی← محلات",
        "مرکزی← نوبران",
        "مرکزی← فراهان",
        "مرکزی← کمیجان",
        "مرکزی← شازند",
        "مرکزی← سربند",
        "مرکزی← ساوه",
        "مرکزی← زرندیه",
        "مرکزی← دلیجان",
        "مرکزی← خنداب",
        "مرکزی← خمین",
        "مرکزی← تفرش",
        "مرکزی← آشتیان",
        "مرکزی← ناحیه 1 اراک",
        "مرکزی← ناحیه 2 اراک",
        "هرمزگان← هرمزگان",
        "هرمزگان← بستک",
        "هرمزگان← بشاگرد",
        "هرمزگان← بندرخمیر",
        "هرمزگان← بندرلنگه",
        "هرمزگان← ناحیه یک بندرعباس",
        "هرمزگان← ناحیه دو بندرعباس",
        "هرمزگان← پارسیان",
        "هرمزگان← جاسک",
        "هرمزگان← جناح",
        "هرمزگان← حاجی آباد",
        "هرمزگان← رودان",
        "هرمزگان← رودخانه",
        "هرمزگان← سندرک",
        "هرمزگان← سیریک",
        "هرمزگان← شهاب",
        "هرمزگان← فین",
        "هرمزگان← قشم",
        "هرمزگان← کیش",
        "هرمزگان← میناب",
        "هرمزگان← هرمز",
        "همدان← همدان",
        "همدان← ناحیه یک همدان",
        "همدان← ناحیه دو همدان",
        "همدان← اسدآباد",
        "همدان← رزن",
        "همدان← بهار",
        "همدان← کبودرآهنگ",
        "همدان← ملایر",
        "همدان← تویسرکان",
        "همدان← نهاوند",
        "همدان← فامنین",
        "همدان← قهاوند",
        "همدان← سردرود",
        "همدان← سامن",
        "همدان← خزل",
        "همدان← جوکار",
        "همدان← گل تپه",
        "همدان← قروه درجزین",
        "همدان← قلقل رود",
        "همدان← لالجین",
        "یزد← یزد"
 };

            for (int i = 0; i < city.Length; i++)
            {
                list.Add(city[i].ToString());
            }
            cmbServer.ItemsSource = city;
        }

        private void btnBackup_Click(object sender, RoutedEventArgs e)
        {
            var btnTag = sender as System.Windows.Controls.Button;
            switch (btnTag.Tag)
            {
                case "Backup":
                    takeBackup();
                    break;

                case "Restore":
                    dbRestore();
                    break;
            }
        }
        private void dbRestore()
        {
            try
            {
               var openFileDialog1 = new System.Windows.Forms.OpenFileDialog();

                openFileDialog1.Filter = "Backup files (*.db)|*.db";
                openFileDialog1.FilterIndex = 1;
                openFileDialog1.RestoreDirectory = true;

                if (openFileDialog1.ShowDialog() == System.Windows.Forms.DialogResult.OK)
                {
                    System.IO.File.Copy(openFileDialog1.FileName, AppVariable.fileName + @"\data.db", true);
                    MainWindow.main.ShowBackupNotification(true,"بازگردانی اطلاعات ");
                }
            }
            catch (Exception)
            {

                MainWindow.main.ShowBackupNotification(false, "بازگردانی اطلاعات ");
            }

        }
        private void takeBackup()
        {
            try
            {
                var saveFileDialog1 = new System.Windows.Forms.SaveFileDialog();
                saveFileDialog1.Filter = "DataBase Backup|*.db";
                saveFileDialog1.Title = "Save an Backup File";
                saveFileDialog1.FileName = "data" + DateTime.Now.ToShortDateString().Replace("/", "-");
                saveFileDialog1.ShowDialog();
                if (saveFileDialog1.FileName != "")
                {
                    using (var source = new SQLiteConnection(@"Data Source=|DataDirectory|\data.db; Version=3;"))
                    using (var destination = new SQLiteConnection("Data Source=" + saveFileDialog1.FileName + "; Version=3;"))
                    {
                        source.Open();
                        destination.Open();
                        source.BackupDatabase(destination, "main", "main", -1, null, 0);
                    }
                }
                MainWindow.main.ShowBackupNotification(true, "پشتیبان گیری از اطلاعات ");
            }
            catch (Exception)
            {
                MainWindow.main.ShowBackupNotification(false, "پشتیبان گیری از اطلاعات ");
            }

        }
    }
}